# Generated by Django 5.0.2 on 2024-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
