# Generated by Django 5.0.2 on 2024-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='freelance',
            field=models.CharField(blank=True, choices=[('Available for freelance', 'freelance'), ('Not available for freelance', 'job')], max_length=50, null=True),
        ),
    ]
